#########
version: '3'
services:
  node_server:
    image: nipunshaji190/node_server:test
    build: ./server
    environment:
      - DB_URL=mongodb+srv://root:toor@cluster0.51apq.mongodb.net/tododb?retryWrites=true&w=majority
    ports:
      - '9000:9000'
    # logging:
    #   driver: awslogs 
  next_client:
    image: nipunshaji190/next_client:test
    # image: nipunshaji190/next_client.slim:latest
    build: ./client
    depends_on:
      - node_server
    ports:
      - '3000:3000'
    # logging:
    #   driver: awslogs  
  reverse-proxy:
    image: nipunshaji190/reverse_proxy:latest
    build: ./reverse_proxy
    container_name: reverse_proxy
    depends_on:
      - next_client
      - node_server
    ports:
      - 80:80
  cypress:
    image: nipunshaji190/cypress-test:test
    build: ./cypress-test
    network_mode: host
    depends_on:
      - next_client
      - node_server
      - reverse-proxy
